spring:
  application:
    name: Arca exercice
  batch:
    job:
      enabled : false
server:
    port: 8080
logging:
  level:
    com.arca: DEBUG

db:
  name: arca
  address: 192.168.0.21
  port: 27017

file:
  path: "D:\\data.txt"